# Generated by Django 5.2.1 on 2025-08-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(default='2025-26', max_length=10),
        ),
    ]
