# Generated by Django 6.0.1 on 2026-03-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_course_off_cycle_timeslot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('course', 'day')},
        ),
    ]
