# Generated by Django 5.2.1 on 2025-11-27 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_role_historylog_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historylog',
            name='topic',
            field=models.CharField(choices=[('course_term', 'Course Term'), ('course_code', 'Course Code'), ('course_number', 'Course Number'), ('course_section', 'Course Section'), ('course_time', 'Course Time'), ('course_year', 'Course Year'), ('major_name', 'Major Name')], max_length=20),
        ),
        migrations.RenameModel(
            old_name='ProgramName',
            new_name='MajorName',
        ),
        migrations.RenameModel(
            old_name='ProgramYearLevel',
            new_name='MajorYearLevel',
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(blank=True, related_name='majors', to='scheduler.course')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.majorname')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.majoryearlevel')),
            ],
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
