# Generated by Django 5.2.1 on 2025-08-15 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_course_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scheduler.courseyear'),
        ),
    ]
