# Generated by Django 5.2.1 on 2025-08-15 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='scheduler.courseyear'),
            preserve_default=False,
        ),
    ]
